### ISSUE TITLE
Sample PDF

### ISSUE THREAD

**Issue by chrislupo** [CalPolyCSC/thesis-template#12]
I might end up owning this, but it's worth describing anyway. Many latex templates include a meta-pdf, that describes the package, but in the format that the output should appear in. So I suggest a PDF included in the repo that shows what the finalized thesis document should look like, that is also the documentation for the repo.

**Comment by WardenGnaw** [comment]
Since the pdf is ultimately judged by Digital Commons in the end, it should look like what they ask for? Which they arbitrary change every couple years I guess?

[Master's Thesis Formatting Guidelines](https://issuu.com/cont-ed/docs/cpgrad_master_sthesisformattingguid)

**Comment by chrislupo** [comment]
Yes, the PDF should look like what MS students have to submit to Digital Commons. And yes, changes may happen, but not that frequently (once since I'm here). The idea is to have all / most of the stuff a CS student would have in a thesis: tables, figures, equations, code listings, algorithms, etc., in the proper format.

**Comment by WardenGnaw** [comment]
I would also recommend having the associated LaTeX with it, so students can easily copy and paste it. 

Could include an examples folder and in it the tex and pdf.

**Comment by jmcgover** [comment]
Examples of the relevant environments, packages, convenient commands (especially the last minute "I just want this to work *now*" ones), macro creation, etc. are crucial to making this an effective template as well as some sanity tactics for code organization. A great example is the [ACM sigconf template](https://github.com/CalPoly/thesis-template/files/792642/sample-sigconf.pdf), taken from [the ACM template website](https://www.acm.org/publications/proceedings-template). 

**LaTeX should not be significantly more difficult to use than Microsoft Word**, especially for computer-science-savvy students. Too often, it is. This should be our guiding principle in building a concise and informative template example.

In addition to specific LaTeX examples, it should contain much of the stuff that is in the Formatting Guidelines. Probably not details about the margins and spacing (things already taken care of by the template), but more of the usage and issues to avoid that students have direct control over.

I'm familiar with the document Dr. Lupo recommends. I'm willing to take this on, but need to finish my own thesis first and have the format enforcers put me through the paces to make sure I don't miss any crucial details in the example. April would be the earliest I could get one put together. 

If someone wants to make one before April, I'll add to it from my own LaTeX experience and formatting journey.

**Comment by AndrewGuenther** [comment]
We can actually set this up with a pretty nasty hack on top of the current CI setup. As a first step, we can take the existing template output pdf and upload it to S3 and just keep a static link to it in the README. That way, every time we push a change to the repo, Travis will just upload a new pdf to S3.

We could just create a few sample chapters to show off all of the snazzy features, and Travis will ensure that the PDF is at least build successfully. I may even be able to swing a way to preview the output PDF on each pull request. We'll see.

**Comment by lacraft** [comment]
Was this example PDF created? It would be helpful to be able to see LaTex examples for the chapter formatting and for adding to the table of contents while using this template. I have not been able to find an example PDF. Thank you!

**Comment by WardenGnaw** [comment]
Since this issue is still active, there is no example PDF available. 
However, you download this repository and upload it to [Overleaf](https://www.overleaf.com/) to see it.

For an update 3 years later and with many updates. This can migrate to use GitHub Actions. It should be easy to generate the pdf and publish an artifact to keep it updated / have it all integrated in GitHub.
