### ISSUE TITLE
Open template permissions

### ISSUE THREAD

**Issue by alexkost819** [CalPolyCSC/thesis-template#15]
I created a branch on my local machine but can't push it up and open it for peer review. Is there a way I can improve the template? I have three minor commits that would add value to the template and make them more in-line with Cal Poly's expectations.

**Comment by AndrewGuenther** [comment]
I'm going to close this since there hasn't been any recent activity. @alexkost819 feel free to reopen if you have any more questions.

**Comment by alexkost819** [comment]
Thanks, will do. Expect a PR tonight, sorry for not understanding the
permissions system in place!

**Comment by AndrewGuenther** [comment]
No problem! Let me know if you have any issues opening the PR
