### ISSUE TITLE
Hanging Indent For Bibliography

### ISSUE THREAD

**Issue by aadriance** [CalPolyCSC/thesis-template#17]
The initial edit pass of my thesis requested that I add hanging indents to the bibliography.  After some searching I was able to fix it using:

```
\def\bibindent{1em}
\begin{thebibliography}{99\kern\bibindent}
\makeatletter
\let\old@biblabel\@biblabel
\def\@biblabel#1{\old@biblabel{#1}\kern\bibindent}
\let\old@bibitem\bibitem
\def\bibitem#1{\old@bibitem{#1}\leavevmode\kern-\bibindent}
\makeatother

\bibliography{bibliography}
\end{thebibliography}
```

Is there a better way to do this?  If not I can make an edit to the main.tex once I know my hanging indents pass the final editorial inspection.

**Comment by AndrewGuenther** [comment]
My attitude with LaTeX has always been "if it works it works." Feel free to submit a PR after inspection and I'll merge it in.

**Comment by ddmarshall** [comment]
Closing this as resolved. #47 produces a format reviewed by grad. ed., and there were no concerns about the current indentation of the bibliography entries.
