### ISSUE TITLE
Subsubsection Numbering

### ISSUE THREAD

**Issue by sarahpadlipsky** [CalPolyCSC/thesis-template#20]
Rejected from Digital Commons because the subsubsections are not numbered or in the TOC. Any suggestions?

"(5-6): Please be sure that all sections are labeled and taken account for in the Table of Contents. It appears that there are some sections throughout this thesis that are not numerically labeled. Please make sure to numerically label all sections and list them in the Table of Contents."

**Comment by corymayer** [comment]
I got the same comments. The changes in this PR fix it: #21

**Comment by AndrewGuenther** [comment]
#21 has been merged. All good here!
