### ISSUE TITLE
Multi line title pushes date to next page

### ISSUE THREAD

**Issue by rnett** [CalPolyCSC/thesis-template#27]
Having a title (in `frontmatter.tex`) that doesn't fit on one line will push the date onto the next page.  Workaround is adding `\vspace{-0.7cm}` to the title text.

**Comment by 2justinmorgan** [comment]
This temp fix worked for me. Thanks @rnett

**Comment by mathurma** [comment]
> Having a title (in `frontmatter.tex`) that doesn't fit on one line will push the date onto the next page. Workaround is adding `\vspace{-0.7cm}` to the title text.

I noticed this solution lifts the title up on the page wherever it occurs, making it misaligned with other text. 
Instead, you can decrease the space between the title and presentation line to account for additional lines of title text.
Changing the corresponding `\addvspace{}` (line 341 in `ucthesis.cls`) from 1.4 to 1.1 works for my 2-line title.

**Comment by kevindirect** [comment]
I had this problem and changed "ucthesis.cls" like this:
>        In Partial Fulfillment \par
>        of the Requirements for the Degree \par
> 
>        \@degree~in~\@field
>        \addvspace{0.35in} % changed this value from 0.65 to 0.35
>
>        by \par
>  ...

I removed 0.05 in from the vspace between the "degree in.." to "by..." until the degree month and year fit on the title page.

**Comment by ddmarshall** [comment]
#40 appears to fix this issue.
