### ISSUE TITLE
[Question] Un-bold List of Tables

### ISSUE THREAD

**Issue by askiefer** [CalPolyCSC/thesis-template#38]
Cal Poly's graduate department does not allow bolding on the preliminary pages. I recently used this template and saw the List of Figures is not bold but the List of Tables is, so I am trying to remove the bold for this. The Figures and Tables list latex looks the same as far as I can tell here - https://github.com/CalPolyCSC/thesis-template/blob/master/ucthesis.cls#L969.

Any idea how I can un-bold the list items in the List of Tables list?

<img width="509" alt="Screenshot 2024-04-05 at 3 47 48 PM" src="https://github.com/CalPolyCSC/thesis-template/assets/13832695/f45a7628-317f-47a3-8478-922ab10eac8a">

**Comment by ddmarshall** [comment]
Can you provide a minimum working example that demonstrates this problem? I thought it might be associated with hyperref, but even changing [these lines](https://github.com/CalPolyCSC/thesis-template/blob/fd934b7e06134e762734357f2b05b94df286c5f6/main.tex#L95) in main.tex I cannot replicate this problem. Here is what I get for a list of tables.
![image](https://github.com/CalPolyCSC/thesis-template/assets/3270505/16ad868e-54aa-436c-b831-0a8b4ed9724b)

**Comment by ddmarshall** [comment]
Closing this as resolved since #47 provides a thesis format reviewed by grad. ed., and the list of tables is not bold.
